apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-rest-api
  template:
    metadata:
      labels:
        app: go-rest-api
    spec:
      containers:
        - name: go-container
          image: berkakipek96/go-rest-api:1.0
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: "1"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc
