POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1haWxAZXhhbXBsZS5jb20iLCJleHAiOjE3MTg2NzM1ODIsInVzZXJJZCI6MH0.KVEOjZicz8mmMjsUg1LAObRYXOv4nLkqwn0VqNgnCIc

{
    "name": "Test Event",
    "description": "A test Event",
    "location": "A test location",
    "datetime": "2024-06-17T10:17:26Z"
}
